running the interactive prompt / 'python -m hypchat' gave an Traceback when there was no configuration file(s) but the environment variable was defined:
	$ HIPCHAT_TOKEN=SvHG...... python -m hypchat
	Traceback (most recent call last):
	.....
	    raise NoSectionError(section)
	ConfigParser.NoSectionError: No section: 'HipChat'

	$ vi  ~/.hypchat
	$ cat  ~/.hypchat
	[HipChat]
	token = faketoke

	$ HIPCHAT_TOKEN=SvHG...... python -m hypchat
	Python 2.7.5 (default, Mar  9 2014, 22:15:05)
	Type "copyright", "credits" or "license" for more information.

	IPython 2.1.0 -- An enhanced Interactive Python.
	?         -> Introduction and overview of IPython's features.
	%quickref -> Quick reference.
	help      -> Python's own help system.
	object?   -> Details about 'object', use 'object??' for extra details.

	In [1]: AUTH_TOKEN
	Out[1]: 'SvHG......'